"""
05_tables/generate_tables.py

Generate all four paper tables from processed CSV outputs.
No values are hard-coded; all data is read from CSV files.

Input (data/tables/):
    Design_Rainfall_Intensities_Selected.csv   <- official IDF benchmark

Input (data/processed/):
    imerg_idf_2000_2019_gumbel.csv             <- IMERG Gumbel-fitted intensities
    comparison_2000_2019_vs_2020_2024.csv      <- temporal stability statistics
    bootstrap_ci.csv                           <- from compute_bootstrap_ci.py
    kirpich_tc.csv                             <- from compute_kirpich.py

Output (data/tables/):
    idf_comparison.csv
    correction_factors.csv
    temporal_stability.csv
    peak_discharge.csv
    all_tables.xlsx

Tables produced:
    Table 2  Official vs IMERG design rainfall intensities (mm/h)
    Table 3  Duration-specific correction factors with bootstrap 95% CI
    Table 4  Temporal stability: 2000-2019 vs 2020-2024 annual maxima
    Table 5  Rational method peak discharge comparison

Note: Table 1 is the official IDF benchmark image (IDF_TABLE.jpg) and is not
      generated by this script.

Note: Run compute_bootstrap_ci.py and compute_kirpich.py before this script
      to ensure data/processed/bootstrap_ci.csv and kirpich_tc.csv are current.
"""

from pathlib import Path
import pandas as pd
import numpy as np

# ── Paths ─────────────────────────────────────────────────────────────────────
ROOT      = Path(__file__).resolve().parents[1]
TABLES_IN = ROOT / "data" / "tables"
PROCESSED = ROOT / "data" / "processed"
OUT       = ROOT / "data" / "tables"
OUT.mkdir(parents=True, exist_ok=True)

# ── Rational method parameters ────────────────────────────────────────────────
C_RUNOFF         = 0.55
A_KM2            = 3.599
DESIGN_RP        = 10
DESIGN_DUR       = "1h"
DESIGN_DUR_SHORT = "30min"

DUR_ORDER  = {"30min": 1, "1h": 2, "2h": 3, "4h": 4, "24h": 5}
DUR_LABELS = {"30min": "30 min", "1h": "1 h", "2h": "2 h",
              "4h": "4 h", "24h": "24 h"}
RETURN_PERIODS = [5, 10, 25]

# ══════════════════════════════════════════════════════════════════════════════
# Load inputs
# ══════════════════════════════════════════════════════════════════════════════
print("Loading input files ...")

official = pd.read_csv(TABLES_IN / "Design_Rainfall_Intensities_Selected.csv")
official.columns = official.columns.str.strip()

official_map = {}
for _, row in official.iterrows():
    dur_key = str(row["Duration"]).strip().replace(" ", "")
    official_map[dur_key] = {
        5:  float(row["5-year Return Period (mm/h)"]),
        10: float(row["10-year Return Period (mm/h)"]),
        25: float(row["25-year Return Period (mm/h)"]),
    }

imerg_idf  = pd.read_csv(PROCESSED / "imerg_idf_2000_2019_gumbel.csv")

comparison = pd.read_csv(PROCESSED / "comparison_2000_2019_vs_2020_2024.csv")
comparison["_order"] = comparison["duration"].map(DUR_ORDER)
comparison = comparison.sort_values("_order").drop(columns="_order")

# Bootstrap CI keyed by duration label e.g. "30min"
bootstrap  = pd.read_csv(PROCESSED / "bootstrap_ci.csv")
bootstrap  = bootstrap.set_index("duration")

# Kirpich results
kirpich    = pd.read_csv(PROCESSED / "kirpich_tc.csv").iloc[0]
print(f"  Kirpich Tc = {kirpich['kirpich_tc_min']:.1f} min  "
      f"(L={kirpich['flow_path_length_m']:.0f} m, "
      f"S={kirpich['slope_pct']:.2f}%)")

durations = sorted(DUR_ORDER.keys(), key=lambda x: DUR_ORDER[x])

# ══════════════════════════════════════════════════════════════════════════════
# TABLE 2  Official vs IMERG IDF comparison
# ══════════════════════════════════════════════════════════════════════════════
print("Building Table 2 ...")
rows_t2 = []
for dur in durations:
    if dur not in official_map:
        continue
    row = {"Duration": DUR_LABELS[dur]}
    for rp in RETURN_PERIODS:
        off_val   = official_map[dur][rp]
        imerg_val = imerg_idf.loc[
            (imerg_idf["duration"] == dur) &
            (imerg_idf["return_period_year"] == rp),
            "imerg_intensity_mm_per_hr"
        ]
        imerg_val = float(imerg_val.iloc[0]) if len(imerg_val) else np.nan
        ratio     = off_val / imerg_val if imerg_val > 0 else np.nan
        row[f"Official_{rp}y (mm/h)"] = round(off_val,   2)
        row[f"IMERG_{rp}y (mm/h)"]    = round(imerg_val, 2)
        row[f"Ratio_{rp}y"]           = round(ratio,     2)
    rows_t2.append(row)

table2 = pd.DataFrame(rows_t2)
table2.to_csv(OUT / "idf_comparison.csv", index=False)
print(f"  Saved -> idf_comparison.csv  ({len(table2)} rows)")

# ══════════════════════════════════════════════════════════════════════════════
# TABLE 3  Duration-specific correction factors with bootstrap 95% CI
# ══════════════════════════════════════════════════════════════════════════════
print("Building Table 3 ...")

INTERP = {
    "30min": "Severe underestimation in raw IMERG",
    "1h":    "Major underestimation in primary design duration",
    "2h":    "Substantial underestimation",
    "4h":    "Moderate underestimation",
    "24h":   "Relatively small mismatch",
}

rows_t3 = []
for dur in durations:
    if dur not in official_map:
        continue
    ratios = []
    for rp in RETURN_PERIODS:
        off_val   = official_map[dur][rp]
        imerg_val = imerg_idf.loc[
            (imerg_idf["duration"] == dur) &
            (imerg_idf["return_period_year"] == rp),
            "imerg_intensity_mm_per_hr"
        ]
        if len(imerg_val) and float(imerg_val.iloc[0]) > 0:
            ratios.append(off_val / float(imerg_val.iloc[0]))

    alpha_d = round(float(np.mean(ratios)), 2) if ratios else np.nan

    # Bootstrap CI from precomputed CSV
    if dur in bootstrap.index:
        ci_lo = bootstrap.loc[dur, "ci_lower_95"]
        ci_hi = bootstrap.loc[dur, "ci_upper_95"]
        ci_str = f"{ci_lo}-{ci_hi}"
    else:
        ci_lo, ci_hi, ci_str = np.nan, np.nan, "N/A"

    rows_t3.append({
        "Duration":                    DUR_LABELS[dur],
        "Correction factor (alpha_d)": alpha_d,
        "95% CI (lower)":              ci_lo,
        "95% CI (upper)":              ci_hi,
        "95% CI":                      ci_str,
        "Interpretation":              INTERP.get(dur, ""),
    })

table3 = pd.DataFrame(rows_t3)
table3.to_csv(OUT / "correction_factors.csv", index=False)
print(f"  Saved -> correction_factors.csv  ({len(table3)} rows)")

# ══════════════════════════════════════════════════════════════════════════════
# TABLE 4  Temporal stability: 2000-2019 vs 2020-2024
# ══════════════════════════════════════════════════════════════════════════════
print("Building Table 4 ...")

table4 = comparison[[
    "duration",
    "mean_2000_2019", "mean_2020_2024", "mean_change_pct",
    "max_2000_2019",  "max_2020_2024",  "max_change_pct",
]].copy()
table4["duration"] = table4["duration"].map(DUR_LABELS).fillna(table4["duration"])
table4.columns = [
    "Duration",
    "Mean 2000-2019 (mm/h)", "Mean 2020-2024 (mm/h)", "Mean Change (%)",
    "Max 2000-2019 (mm/h)",  "Max 2020-2024 (mm/h)",  "Max Change (%)",
]
for col in table4.columns[1:]:
    table4[col] = table4[col].round(2)
table4.to_csv(OUT / "temporal_stability.csv", index=False)
print(f"  Saved -> temporal_stability.csv  ({len(table4)} rows)")

# ══════════════════════════════════════════════════════════════════════════════
# TABLE 5  Peak discharge
# ══════════════════════════════════════════════════════════════════════════════
print("Building Table 5 ...")

def rational_Q(i_mm_h, C, A_km2):
    """Peak discharge Q (m3/s) = C * i (mm/h) * A (km2) / 3.6"""
    return round(C * i_mm_h * A_km2 / 3.6, 2)

# Primary design duration: 1 h
imerg_raw_i = imerg_idf.loc[
    (imerg_idf["duration"] == DESIGN_DUR) &
    (imerg_idf["return_period_year"] == DESIGN_RP),
    "imerg_intensity_mm_per_hr"
]
imerg_raw_i = float(imerg_raw_i.iloc[0]) if len(imerg_raw_i) else np.nan
official_i  = official_map.get(DESIGN_DUR, {}).get(DESIGN_RP, np.nan)

# Short-duration sensitivity: 30 min
imerg_raw_i_short = imerg_idf.loc[
    (imerg_idf["duration"] == DESIGN_DUR_SHORT) &
    (imerg_idf["return_period_year"] == DESIGN_RP),
    "imerg_intensity_mm_per_hr"
]
imerg_raw_i_short = float(imerg_raw_i_short.iloc[0]) if len(imerg_raw_i_short) else np.nan
official_i_short  = official_map.get(DESIGN_DUR_SHORT, {}).get(DESIGN_RP, np.nan)

rows_t5 = [
    {
        "Scenario":                  "Raw IMERG (1 h)",
        "Rainfall intensity (mm/h)": round(imerg_raw_i, 2),
        "Runoff coefficient C":      C_RUNOFF,
        "Catchment area (km2)":      A_KM2,
        "Peak discharge Q (m3/s)":   rational_Q(imerg_raw_i, C_RUNOFF, A_KM2),
    },
    {
        "Scenario":                  "Benchmark-corrected IMERG (1 h)",
        "Rainfall intensity (mm/h)": round(official_i, 2),
        "Runoff coefficient C":      C_RUNOFF,
        "Catchment area (km2)":      A_KM2,
        "Peak discharge Q (m3/s)":   rational_Q(official_i, C_RUNOFF, A_KM2),
    },
    {
        "Scenario":                  "Raw IMERG (30 min)",
        "Rainfall intensity (mm/h)": round(imerg_raw_i_short, 2),
        "Runoff coefficient C":      C_RUNOFF,
        "Catchment area (km2)":      A_KM2,
        "Peak discharge Q (m3/s)":   rational_Q(imerg_raw_i_short, C_RUNOFF, A_KM2),
    },
    {
        "Scenario":                  "Benchmark-corrected IMERG (30 min)",
        "Rainfall intensity (mm/h)": round(official_i_short, 2),
        "Runoff coefficient C":      C_RUNOFF,
        "Catchment area (km2)":      A_KM2,
        "Peak discharge Q (m3/s)":   rational_Q(official_i_short, C_RUNOFF, A_KM2),
    },
]
table5 = pd.DataFrame(rows_t5)
table5.to_csv(OUT / "peak_discharge.csv", index=False)
print(f"  Saved -> peak_discharge.csv  ({len(table5)} rows)")

# ══════════════════════════════════════════════════════════════════════════════
# Excel workbook — all four tables on separate sheets
# ══════════════════════════════════════════════════════════════════════════════
print("Exporting all_tables.xlsx ...")
with pd.ExcelWriter(OUT / "all_tables.xlsx", engine="openpyxl") as writer:
    table2.to_excel(writer, sheet_name="Table2_IDF_Comparison",     index=False)
    table3.to_excel(writer, sheet_name="Table3_Correction_Factors", index=False)
    table4.to_excel(writer, sheet_name="Table4_Temporal_Stability", index=False)
    table5.to_excel(writer, sheet_name="Table5_Peak_Discharge",     index=False)
print("  Saved -> all_tables.xlsx")

# ── Console summary ───────────────────────────────────────────────────────────
for title, tbl in [
    ("TABLE 2  Official vs IMERG IDF (mm/h)", table2),
    ("TABLE 3  Correction Factors with 95% CI", table3),
    ("TABLE 4  Temporal Stability", table4),
    ("TABLE 5  Peak Discharge", table5),
]:
    print(f"\n{'='*60}\n{title}\n{'='*60}")
    print(tbl.to_string(index=False))

print(f"\nAll outputs saved to: {OUT}")
