"""
05_tables/generate_tables.py

Generate all four generated paper tables from processed CSV outputs.
No values are hard-coded; all data is read from CSV files.

Input (data/tables/):
    Design_Rainfall_Intensities_Selected.csv   <- official IDF benchmark
                                                  (selected values only)

Input (data/processed/):
    imerg_idf_2000_2019_gumbel.csv             <- IMERG Gumbel-fitted intensities
    comparison_2000_2019_vs_2020_2024.csv      <- temporal stability statistics
    bootstrap_ci.csv                           <- from compute_bootstrap_ci.py
    kirpich_tc.csv                             <- from compute_kirpich.py

Output (data/tables/):
    idf_comparison.csv
    correction_factors.csv
    temporal_stability.csv
    peak_discharge.csv
    all_tables.xlsx

Tables produced:
    Table 2  Official vs IMERG design rainfall intensities (mm/h)
    Table 3  Duration-specific correction factors with bootstrap 95% CI
    Table 4  Temporal stability: 2000-2019 vs 2020-2024 annual maxima
    Table 5  Rational method peak discharge comparison

Note: Table 1 of the paper lists the selected official design intensities and is
      taken directly from Design_Rainfall_Intensities_Selected.csv; it is not
      generated by this script.

Note: CSV outputs are written with fixed decimal places so that the manuscript
      tables do not strip trailing zeros (e.g. 2.90 rather than 2.9, 172.0
      rather than 172). The Excel workbook keeps the underlying numeric values
      so that it remains usable for further calculation.

Note: Run compute_bootstrap_ci.py and compute_kirpich.py before this script
      to ensure data/processed/bootstrap_ci.csv and kirpich_tc.csv are current.
"""

from pathlib import Path
import pandas as pd
import numpy as np

# ── Paths ─────────────────────────────────────────────────────────────────────
ROOT      = Path(__file__).resolve().parents[1]
TABLES_IN = ROOT / "data" / "tables"
PROCESSED = ROOT / "data" / "processed"
OUT       = ROOT / "data" / "tables"
OUT.mkdir(parents=True, exist_ok=True)

# ── Rational method parameters ────────────────────────────────────────────────
C_RUNOFF         = 0.55
A_KM2            = 3.599
DESIGN_RP        = 10
DESIGN_DUR       = "1h"
DESIGN_DUR_SHORT = "30min"

DUR_ORDER  = {"30min": 1, "1h": 2, "2h": 3, "4h": 4, "24h": 5}
DUR_LABELS = {"30min": "30 min", "1h": "1 h", "2h": "2 h",
              "4h": "4 h", "24h": "24 h"}
RETURN_PERIODS = [5, 10, 25]

# ── Presentation conventions ──────────────────────────────────────────────────
# En dash for all numeric ranges and year spans, to match the manuscript text.
DASH = "\u2013"
# Decimal places: official benchmark intensities are tabulated to one decimal
# in the source standard; IMERG-derived intensities and all derived quantities
# are reported to two.
DP_OFFICIAL = 1
DP_IMERG    = 2
DP_RATIO    = 2
DP_Q        = 2
DP_PCT      = 1


def fmt(value, decimals):
    """Format a number to a fixed number of decimals; pass non-numerics through."""
    if value is None:
        return ""
    if isinstance(value, str):
        return value
    if isinstance(value, float) and np.isnan(value):
        return "N/A"
    return f"{float(value):.{decimals}f}"


def format_table(df, spec):
    """Return a copy of df with the columns named in spec formatted as strings.

    spec maps column name -> number of decimal places.
    """
    out = df.copy()
    for col, decimals in spec.items():
        if col in out.columns:
            out[col] = out[col].map(lambda v: fmt(v, decimals))
    return out


# ══════════════════════════════════════════════════════════════════════════════
# Load inputs
# ══════════════════════════════════════════════════════════════════════════════
print("Loading input files ...")

official = pd.read_csv(TABLES_IN / "Design_Rainfall_Intensities_Selected.csv")
official.columns = official.columns.str.strip()

official_map = {}
for _, row in official.iterrows():
    dur_key = str(row["Duration"]).strip().replace(" ", "")
    official_map[dur_key] = {
        5:  float(row["5-year Return Period (mm/h)"]),
        10: float(row["10-year Return Period (mm/h)"]),
        25: float(row["25-year Return Period (mm/h)"]),
    }

imerg_idf  = pd.read_csv(PROCESSED / "imerg_idf_2000_2019_gumbel.csv")

comparison = pd.read_csv(PROCESSED / "comparison_2000_2019_vs_2020_2024.csv")
comparison["_order"] = comparison["duration"].map(DUR_ORDER)
comparison = comparison.sort_values("_order").drop(columns="_order")

# Bootstrap CI keyed by duration label e.g. "30min"
bootstrap  = pd.read_csv(PROCESSED / "bootstrap_ci.csv")
bootstrap  = bootstrap.set_index("duration")

# Kirpich results
kirpich    = pd.read_csv(PROCESSED / "kirpich_tc.csv").iloc[0]
print(f"  Kirpich Tc = {kirpich['kirpich_tc_min']:.1f} min  "
      f"(L={kirpich['flow_path_length_m']:.0f} m, "
      f"S={kirpich['slope_pct']:.2f}%)")

durations = sorted(DUR_ORDER.keys(), key=lambda x: DUR_ORDER[x])

# ══════════════════════════════════════════════════════════════════════════════
# TABLE 2  Official vs IMERG IDF comparison
# ══════════════════════════════════════════════════════════════════════════════
print("Building Table 2 ...")
rows_t2 = []
for dur in durations:
    if dur not in official_map:
        continue
    row = {"Duration": DUR_LABELS[dur]}
    for rp in RETURN_PERIODS:
        off_val   = official_map[dur][rp]
        imerg_val = imerg_idf.loc[
            (imerg_idf["duration"] == dur) &
            (imerg_idf["return_period_year"] == rp),
            "imerg_intensity_mm_per_hr"
        ]
        imerg_val = float(imerg_val.iloc[0]) if len(imerg_val) else np.nan
        ratio     = off_val / imerg_val if imerg_val > 0 else np.nan
        row[f"Official_{rp}y (mm/h)"] = off_val
        row[f"IMERG_{rp}y (mm/h)"]    = imerg_val
        row[f"Ratio_{rp}y"]           = ratio
    rows_t2.append(row)

table2 = pd.DataFrame(rows_t2)

t2_spec = {}
for rp in RETURN_PERIODS:
    t2_spec[f"Official_{rp}y (mm/h)"] = DP_OFFICIAL
    t2_spec[f"IMERG_{rp}y (mm/h)"]    = DP_IMERG
    t2_spec[f"Ratio_{rp}y"]           = DP_RATIO
table2_out = format_table(table2, t2_spec)
table2_out.to_csv(OUT / "idf_comparison.csv", index=False)
print(f"  Saved -> idf_comparison.csv  ({len(table2_out)} rows)")

# ══════════════════════════════════════════════════════════════════════════════
# TABLE 3  Duration-specific correction factors with bootstrap 95% CI
# ══════════════════════════════════════════════════════════════════════════════
print("Building Table 3 ...")

INTERP = {
    "30min": "Severe underestimation in raw IMERG",
    "1h":    "Major underestimation in primary design duration",
    "2h":    "Substantial underestimation",
    "4h":    "Moderate underestimation",
    "24h":   "Relatively small mismatch",
}

rows_t3 = []
for dur in durations:
    if dur not in official_map:
        continue
    ratios = []
    for rp in RETURN_PERIODS:
        off_val   = official_map[dur][rp]
        imerg_val = imerg_idf.loc[
            (imerg_idf["duration"] == dur) &
            (imerg_idf["return_period_year"] == rp),
            "imerg_intensity_mm_per_hr"
        ]
        if len(imerg_val) and float(imerg_val.iloc[0]) > 0:
            ratios.append(off_val / float(imerg_val.iloc[0]))

    alpha_d = float(np.mean(ratios)) if ratios else np.nan

    # Bootstrap CI from precomputed CSV. Reported as a single interval column;
    # the separate lower/upper columns were removed because they duplicated it.
    if dur in bootstrap.index:
        ci_lo = float(bootstrap.loc[dur, "ci_lower_95"])
        ci_hi = float(bootstrap.loc[dur, "ci_upper_95"])
        ci_str = f"{fmt(ci_lo, DP_RATIO)}{DASH}{fmt(ci_hi, DP_RATIO)}"
    else:
        ci_lo, ci_hi, ci_str = np.nan, np.nan, "N/A"

    rows_t3.append({
        "Duration":                       DUR_LABELS[dur],
        "Correction factor (\u03b1_d)":   alpha_d,
        "95% CI":                         ci_str,
        "Interpretation":                 INTERP.get(dur, ""),
        # kept for the Excel workbook only, dropped from the manuscript table
        "_ci_lower": ci_lo,
        "_ci_upper": ci_hi,
    })

table3 = pd.DataFrame(rows_t3)

table3_out = format_table(
    table3.drop(columns=["_ci_lower", "_ci_upper"]),
    {"Correction factor (\u03b1_d)": DP_RATIO},
)
table3_out.to_csv(OUT / "correction_factors.csv", index=False)
print(f"  Saved -> correction_factors.csv  ({len(table3_out)} rows)")

# ══════════════════════════════════════════════════════════════════════════════
# TABLE 4  Temporal stability: 2000-2019 vs 2020-2024
# ══════════════════════════════════════════════════════════════════════════════
print("Building Table 4 ...")

table4 = comparison[[
    "duration",
    "mean_2000_2019", "mean_2020_2024", "mean_change_pct",
    "max_2000_2019",  "max_2020_2024",  "max_change_pct",
]].copy()
table4["duration"] = table4["duration"].map(DUR_LABELS).fillna(table4["duration"])
table4.columns = [
    "Duration",
    f"Mean 2000{DASH}2019 (mm/h)", f"Mean 2020{DASH}2024 (mm/h)", "Mean change (%)",
    f"Max 2000{DASH}2019 (mm/h)",  f"Max 2020{DASH}2024 (mm/h)",  "Max change (%)",
]

t4_spec = {
    f"Mean 2000{DASH}2019 (mm/h)": DP_IMERG,
    f"Mean 2020{DASH}2024 (mm/h)": DP_IMERG,
    "Mean change (%)":             DP_PCT,
    f"Max 2000{DASH}2019 (mm/h)":  DP_IMERG,
    f"Max 2020{DASH}2024 (mm/h)":  DP_IMERG,
    "Max change (%)":              DP_PCT,
}
table4_out = format_table(table4, t4_spec)
table4_out.to_csv(OUT / "temporal_stability.csv", index=False)
print(f"  Saved -> temporal_stability.csv  ({len(table4_out)} rows)")

# ══════════════════════════════════════════════════════════════════════════════
# TABLE 5  Peak discharge
# ══════════════════════════════════════════════════════════════════════════════
print("Building Table 5 ...")

def rational_Q(i_mm_h, C, A_km2):
    """Peak discharge Q (m3/s) = C * i (mm/h) * A (km2) / 3.6"""
    return C * i_mm_h * A_km2 / 3.6

# Primary design duration: 1 h
imerg_raw_i = imerg_idf.loc[
    (imerg_idf["duration"] == DESIGN_DUR) &
    (imerg_idf["return_period_year"] == DESIGN_RP),
    "imerg_intensity_mm_per_hr"
]
imerg_raw_i = float(imerg_raw_i.iloc[0]) if len(imerg_raw_i) else np.nan
official_i  = official_map.get(DESIGN_DUR, {}).get(DESIGN_RP, np.nan)

# Short-duration sensitivity: 30 min
imerg_raw_i_short = imerg_idf.loc[
    (imerg_idf["duration"] == DESIGN_DUR_SHORT) &
    (imerg_idf["return_period_year"] == DESIGN_RP),
    "imerg_intensity_mm_per_hr"
]
imerg_raw_i_short = float(imerg_raw_i_short.iloc[0]) if len(imerg_raw_i_short) else np.nan
official_i_short  = official_map.get(DESIGN_DUR_SHORT, {}).get(DESIGN_RP, np.nan)

# Underestimation: (corrected - raw) / corrected * 100
# Computed from intensity; identical to discharge underestimation (Q = CiA/3.6,
# C and A are constant, so the ratio cancels and the percentage is the same).
# The per-cent sign is carried by the column header, not by the cell values.
under_1h    = (official_i       - imerg_raw_i)       / official_i       * 100
under_30min = (official_i_short - imerg_raw_i_short) / official_i_short * 100

rows_t5 = [
    {
        "Scenario":                  "Raw IMERG (1 h)",
        "Rainfall intensity (mm/h)": imerg_raw_i,
        "Runoff coefficient C":      C_RUNOFF,
        "Catchment area (km2)":      A_KM2,
        "Peak discharge Q (m3/s)":   rational_Q(imerg_raw_i, C_RUNOFF, A_KM2),
        "Underestimation (%)":       under_1h,
    },
    {
        "Scenario":                  "Benchmark-corrected IMERG (1 h)",
        "Rainfall intensity (mm/h)": official_i,
        "Runoff coefficient C":      C_RUNOFF,
        "Catchment area (km2)":      A_KM2,
        "Peak discharge Q (m3/s)":   rational_Q(official_i, C_RUNOFF, A_KM2),
        "Underestimation (%)":       "\u2014",
    },
    {
        "Scenario":                  "Raw IMERG (30 min)",
        "Rainfall intensity (mm/h)": imerg_raw_i_short,
        "Runoff coefficient C":      C_RUNOFF,
        "Catchment area (km2)":      A_KM2,
        "Peak discharge Q (m3/s)":   rational_Q(imerg_raw_i_short, C_RUNOFF, A_KM2),
        "Underestimation (%)":       under_30min,
    },
    {
        "Scenario":                  "Benchmark-corrected IMERG (30 min)",
        "Rainfall intensity (mm/h)": official_i_short,
        "Runoff coefficient C":      C_RUNOFF,
        "Catchment area (km2)":      A_KM2,
        "Peak discharge Q (m3/s)":   rational_Q(official_i_short, C_RUNOFF, A_KM2),
        "Underestimation (%)":       "\u2014",
    },
]
table5 = pd.DataFrame(rows_t5)

table5_out = format_table(table5, {
    "Peak discharge Q (m3/s)": DP_Q,
    "Underestimation (%)":     DP_PCT,
})
# The intensity column mixes two provenances: the raw IMERG rows are
# Gumbel-fitted values reported to two decimals, the benchmark-corrected rows
# are the official tabulated intensities, which the source standard gives to
# one. Each value is therefore formatted to the precision it actually carries,
# so that every figure matches Table 2 and the manuscript text exactly.
T5_INTENSITY_DP = [DP_IMERG, DP_OFFICIAL, DP_IMERG, DP_OFFICIAL]
table5_out["Rainfall intensity (mm/h)"] = [
    fmt(v, dp) for v, dp in
    zip(table5["Rainfall intensity (mm/h)"], T5_INTENSITY_DP)
]
table5_out.to_csv(OUT / "peak_discharge.csv", index=False)
print(f"  Saved -> peak_discharge.csv  ({len(table5_out)} rows)")

# ══════════════════════════════════════════════════════════════════════════════
# Excel workbook — numeric values retained for further calculation
# ══════════════════════════════════════════════════════════════════════════════
print("Exporting all_tables.xlsx ...")
with pd.ExcelWriter(OUT / "all_tables.xlsx", engine="openpyxl") as writer:
    table2.to_excel(writer, sheet_name="Table2_IDF_Comparison",     index=False)
    table3.to_excel(writer, sheet_name="Table3_Correction_Factors", index=False)
    table4.to_excel(writer, sheet_name="Table4_Temporal_Stability", index=False)
    table5.to_excel(writer, sheet_name="Table5_Peak_Discharge",     index=False)
print("  Saved -> all_tables.xlsx")

# ── Console summary ───────────────────────────────────────────────────────────
for title, tbl in [
    ("TABLE 2  Official vs IMERG IDF (mm/h)", table2_out),
    ("TABLE 3  Correction Factors with 95% CI", table3_out),
    ("TABLE 4  Temporal Stability", table4_out),
    ("TABLE 5  Peak Discharge", table5_out),
]:
    print(f"\n{'='*60}\n{title}\n{'='*60}")
    print(tbl.to_string(index=False))

print(f"\nAll outputs saved to: {OUT}")
